name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: app-001-step3-1-suzuyu-node-29  # あなたのWeb App名
  PYTHON_VERSION: '3.8'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Procfile
        run: echo "web: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app" > Procfile

      - name: Zip application for deployment
        run: |
          zip -r app.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
